adding startup instructions to README
CodeTheDream/ride-share-rails pull request #297
Opened 2020-11-30 17:51 UTC by kidatsy

2020-11-30 18:53 UTC, jrmcgarvey requested changes
See comments to the changed file.

2020-11-30 18:53 UTC, jrmcgarvey commented on README.md
> +Get the right credentials and master key from one of the main devs on the project. Run the following to make sure the credentials are set correctly. Otherwise, the seeder will complain about not havi
Actually, the only credential you need to get from another developer is the master.key file.  The other credentials are already delivered when you do the git clone or fork, encrypted with the master key, in credentials.yml.enc.

2020-11-30 18:53 UTC, jrmcgarvey commented on README.md
> +Clone it.
Actually, our process for this repository is different.  Only a few people have write access to the repository.  So, to get started as a developer, you must first fork the repository and then clone from the fork.  On the local machine, it is necessary to configure a git remote for 'upstream' so that people can merge before they submit PRs.  The upstream repository is the master, as in the URL below. The origin repository is the fork.  You submit PRs from the fork.

2020-12-02 16:26 UTC, kidatsy commented on README.md
> +Clone it.
Ok, edits made.

2021-02-28 23:17 UTC, micronix approved these changes
Just clearing out PRs that I'm on. I think the README.md looks good. The only thing is that we have talked about making this repo private. We should probably revisit that conversation.

2021-03-04 21:03 UTC, merged