Added message when google validations id different from enter validation
CodeTheDream/ride-share-rails pull request #306
Opened 2021-01-15 21:05 UTC by Kwasi008

- check old address entered to what google validates

2021-01-18 21:56 UTC, micronix requested changes
Hey @Kwasi008 what is this for? If I understand it correctly. When a user updates a ride and they change the address there is an alert that shows the address changed?

Also can you removed the commented out byebug statements

2021-01-18 21:56 UTC, micronix commented on Gemfile
> +source 'http://rubygems.org'
hey @Kwasi008 why did you changed this to http?

2021-01-19 14:29 UTC, Kwasi008 commented
Hi @micronix, I was working on Jira card 26 which was  "As an admin, I want to confirm riders' addresses after validation when creating rides". I can adjust it if that was the desired goal.

2021-01-21 20:24 UTC, kidatsy commented on spec/requests/rides_spec.rb
> -    byebug
So many old byebugs haha!

2021-01-22 19:41 UTC, Kwasi008 commented
![Screen Shot 2021-01-22 at 2 39 00 PM](https://user-images.githubusercontent.com/34540242/105537412-e2e37b00-5cbf-11eb-991d-c5556c59b43a.png)

2021-01-22 19:44 UTC, Kwasi008 commented
Hi @micronix 
- changed how the flash message was working, we were not accounting for user alerts, we were just accounting for notice and errors and not alerts.
- Changed the controller's flash.alert into flash.errors when it is an error and not an alert.
- Attach a picture to show the changes

2021-01-22 19:46 UTC, Kwasi008 commented
@micronix 
- Added clear flash messages when the page is reloading

2021-01-27 19:06 UTC, kidatsy commented on app/helpers/application_helper.rb
> +      "alert-success"
indentation?

2021-01-27 20:35 UTC, Kwasi008 commented on app/helpers/application_helper.rb
> +      "alert-success"
Thanks TC, I just went through and checked all of them. Please let me know if there anything else I should change on this PR. Thank you

2021-02-01 18:04 UTC, jrmcgarvey approved these changes
Looks OK to me.

2021-02-01 18:04 UTC, merged